server:
  port: 8999
spring:
  application:
    name: gradven-springboot-redis
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 1
      min-idle: 3
      max-active: 10
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  redis:              # REDIS (RedisProperties)
    database: 0       # Redis数据库索引（默认为0）
    host: localhost   # Redis服务器地址
    port: 6379        # Redis服务器连接端口
    password:         # Redis服务器连接密码（默认为空）
    pool:
      max-active: 8   # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1    # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8     # 连接池中的最大空闲连接
      min-idle: 0     # 连接池中的最小空闲连接
    timeout: 30000    # 连接超时时间（毫秒）


mybatis:
  mapper-locations: classpath:/mapping/*Mapper.xml
  type-aliases-package: com.gradven.springboot.redis.model
  executorType: simple

security:
  basic:
    path: /swagger-ui.html
    enabled: true
  user:
    name: admin
    password: 123456


management:
  port: 8999
  address: 127.0.0.1
  context-path: /admin
  security:
    role: SUPERUSER

endpoints:
  shutdown:
    enabled: true
    sensitive: false
    path: /shutdown

logging:
  file: ./tmp/logs/${spring.application.name}.log

